### ISSUE TITLE
Content Load Error on V1.3

### ISSUE THREAD

**Issue by sebzanga** [Danielku15/BetterStartPage#10]
VS's StartPage works fine. Customized show error. Attached screenshot

![betterstartpageerror2](https://cloud.githubusercontent.com/assets/1793823/5216837/ee6d644e-7617-11e4-9535-73c288c77dec.JPG)

**Comment by Danielku15** [comment]
since there was no response anymore and the start page seems to work for all others I'm closing this issue.
