### ISSUE TITLE
Solution group elements are spread evenly, but should be aligned to top

### ISSUE THREAD

**Issue by SylwesterZarebski** [Danielku15/BetterStartPage#20]
Now groups spread all items evenly, but they (items) should be aligned to top (like before).
Is this a regression because of commit dda9383e61712d5a7734b8c923d4e6d3f7e326e3?
Version: Visual Studio 2013, extension 1.10.

**Comment by Danielku15** [comment]
Your description is a bit unprecise. Can you please add some more details how you would expect the layouting to be? 

**Which UI elements are taking about?**
Do you mean the layouting of the whole groups or do you mean the layouting of the items within a single group? 

**Which settings are you using for "Group Columns" and "Project Columns"?**

**What do you mean with `align to top`**
A screenshot would help here. 

Thanks.

**Comment by SylwesterZarebski** [comment]
Sure, screenshots are below:
Group columns: 2, Project columns: 1:
![betterstartpage_bug_1](https://cloud.githubusercontent.com/assets/1755531/18808178/656f0128-825b-11e6-95eb-46c899a9f891.png)

Group columns: 1, Project columns: 1:
![betterstartpage_bug_2](https://cloud.githubusercontent.com/assets/1755531/18808189/b6da79f2-825b-11e6-9c29-180138334eee.png)

**Comment by Danielku15** [comment]
Great, thanks for the screenshots. now it's clear to me. I will work on it today.

**Comment by Danielku15** [comment]
I reintroduced a custom grid for better layouting. Version 1.11 is available for downloading.

**Comment by SylwesterZarebski** [comment]
Thanks a lot!
