### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by Danielku15** [Danielku15/BetterStartPage#23]
VS2017 is out this plugin should be adapted to the new startpage layout

**Comment by BladeMF** [comment]
I am very much looking forward to this! Do you have an ETA?

**Comment by Danielku15** [comment]
I am currently working on it. But it looks like Microsoft made it complicated for me to update my plugin to VS2017. Custom startpages do not get the same data (context) as the default start page.  I have to find a mechanism of creating the necessary data sources.

**Comment by BladeMF** [comment]
What data are you missing? Maybe I can help.
My extension ran as it is on VS 2017, I just added prerequisites.

**Comment by Danielku15** [comment]
Start pages are a very special kind of extension and very badly documented in my opinion. It's easy to make any kind of start page, but if you want to have access to the original components like the MRU list you run into troubles. That's why I lately refactored the code to load the original start page, and simply replace some components in the final UI. It's easier than rebuild the original start page. 

Sadly VS2017 does an explicit check if the start page component is their own control and then they assign some special ViewModels to the individual subcontrols like the MRU list. Those classes are all internal and not accessible. I managed to create some code based on reflection that creates all necessary types. I just commited the required changes some minutes ago. You can check the commit if above if you are interested into details. 

Another problem is now the deployment.  am still using the old vsix manifest schema because there is nowhere documented what the replacement of `<CustomExtension Type="StartPage">StartPage.xaml</CustomExtension>` is in the new format. Sadly for deploying the extension to the Marketplace, it seems the new format is required, otherwise you get an error while uploading: 

![image](https://cloud.githubusercontent.com/assets/674916/23834415/6e6a15a8-0756-11e7-91ca-93a832b9c48c.png)

**Comment by BladeMF** [comment]
You have it way worse than me, it seems. I presume the original start page is not in .NET so you can use reflector and see the source?

**Comment by BladeMF** [comment]
As for the "update your references", I'm guessing they mean this: https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017

**Comment by Danielku15** [comment]
I published a new version, hopefully it works for everybody. I migrated to the new VSIX schema but had to drop VS2010 support for this. With this VS2017 support is complete.

**Comment by BladeMF** [comment]
Perfect!

**Comment by BladeMF** [comment]
It seems to be working. Is there anyway I can migrate my 2015 settings? The registry seems different.

**Comment by Danielku15** [comment]
I likely have to add a feature to export/import configurations. I am using the VS default mechanism for storing/loading settings which ends up in the registry by default.

**Comment by BladeMF** [comment]
Yea, but the 2017 has no registry 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Danielku15** [comment]
I added an export/import feature to the context menu. This way you can migrate your settings faster.

**Comment by BladeMF** [comment]
Thanks. By the way, just for the record - it **does** have a registry, its in a separate file in the AppData/Local/.. directory. You must load it to view it.

**Comment by Danielku15** [comment]
Thanks for the info. I am anyhow considering to write a custom settings file. It is quite annoying how and if VS even saves settings of the settings store I am using. If you have multiple VS open and edit the startpage only in one, the other VS might overwrite the configured start page with the an empty one.
