### ISSUE TITLE
BetterStartPage doesn't show in VS2015 Pro Update 3 after last update

### ISSUE THREAD

**Issue by rbgarcia** [Danielku15/BetterStartPage#24]
Title says it all.

After updating BetterStartPage extension to the latest version, it no longer appears when I open VS. Instead, the default (useless) page appears. Reinstalling and closing/opening VS had no effect.

Where can I get the previous version?
Is this a known issue?

**Comment by Danielku15** [comment]
After updates sometimes VS resets the start page to the default one. Did you select again in the options that BetterStartPage should be used as start page?

**Comment by rbgarcia** [comment]
I feel silly now.
You are right. The option was reset and I have configured so long ago that I no longer remembered about it. It even persisted all my settings. Thanks for the help.
