### ISSUE TITLE
Crashes VS on launch - "System.Windows.Markup.XamlParseException"

### ISSUE THREAD

**Issue by GbeTech** [Danielku15/BetterStartPage#25]
Hi,
After a month+- of using BSP, this happened today - 
I get a "Visual Studio 2017 stopped working" with a "System.Windows.Markup.XamlParseException" exception.

I uploaded a GIF showing the process and two images of the details.
I think it happened because I added some more solutions yesterday. Maybe it was too much.

Also, is there a way to manually edit the start page outside of VS? I'll try to trim it down and see what happens.

Thanks!

![betterstartpage exception](https://user-images.githubusercontent.com/18548473/29305618-51dedc36-81a2-11e7-8c8a-034ec694c3b5.png)

![betterstartpage exception 2](https://user-images.githubusercontent.com/18548473/29305619-52855610-81a2-11e7-82bc-c6828bc4e9fd.png)

![betterstartpage](https://user-images.githubusercontent.com/18548473/29305453-8dc4eac0-81a1-11e7-8901-803f76613522.gif)

**Comment by Danielku15** [comment]
Thanks for the report. I haven't seen this problem before. There is [one place](https://github.com/Danielku15/BetterStartPage/blob/master/BetterStartPage.Control/Converter/PathToSystemIconConverter.cs) where I load the icons for the corresponding file types. The `GetFileIcon` seems to lack of some error handling. I will try to fix it this evening.

**Comment by GbeTech** [comment]
Thanks!

**Comment by Danielku15** [comment]
I added some more error handling and deployed a new version to the market place (v1.14). If this does not fixes the crashes for you, feel free to reopen the issue.

**Comment by GbeTech** [comment]
Alright, I'll be able to check only tomorrow evening (24 hours).
