### ISSUE TITLE
Does not work anymore in VS2017 version 15.5.0 :-(

### ISSUE THREAD

**Issue by rwjdk** [Danielku15/BetterStartPage#28]
I've been using the brilliant extension the last months in VS2017 but with latest 15.5.0 release, the page does not work anymore. It just shows empty "Getting started" and "Recent" :-(

![2017-12-05 08-39-04](https://user-images.githubusercontent.com/7032102/33595303-ccd00c56-d997-11e7-9190-ed9144c648da.png)

![2017-12-05 08-37-39](https://user-images.githubusercontent.com/7032102/33595256-a14e966a-d997-11e7-921d-0e8d24049c64.png)

Hope it is possible to fix

**Comment by SirViver** [comment]
Seems like they've changed quite a bit of the start page internals, causing loads of binding errors:

    System.Windows.Data Error: 40 : BindingExpression path error: 'CodeContainers' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=CodeContainers; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'CategorizedMruListBox' (Name=''); target property is 'DataContext' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'IsExpanded' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=IsExpanded; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Expander' (Name=''); target property is 'IsExpanded' (type 'Boolean')
    System.Windows.Data Error: 40 : BindingExpression path error: 'HideCommand' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=HideCommand; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
    System.Windows.Data Error: 45 : BindingExpression with XPath cannot bind to non-XML object.; XPath='/items/discovercommands/command' BindingExpression:Path=; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ListBox' (Name=''); target property is 'ItemsSource' (type 'IEnumerable') PolicyBasedDataSource:'Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource'
    System.Windows.Data Error: 40 : BindingExpression path error: 'GetStartedItemsDataSource' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=GetStartedItemsDataSource.Links.Content; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ListBox' (Name='Discover_ListView'); target property is 'DataContext' (type 'Object')
    System.Windows.Data Error: 45 : BindingExpression with XPath cannot bind to non-XML object.; XPath='/items/discovercommands/command' BindingExpression:Path=; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ListBox' (Name='Discover_ListView'); target property is 'ItemsSource' (type 'IEnumerable') PolicyBasedDataSource:'Microsoft.Internal.VisualStudio.PlatformUI.PolicyBasedDataSource'
    System.Windows.Data Error: 40 : BindingExpression path error: 'HasProviders' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=HasProviders; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'CodeContainerProvidersListView' (Name='CodeContainerProviderListView'); target property is 'NoTarget' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'Providers' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=Providers; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')
    System.Windows.Data Error: 40 : BindingExpression path error: 'LocalProviders' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=LocalProviders; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')
    System.Windows.Data Error: 40 : BindingExpression path error: 'HasSearchResults' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=HasSearchResults; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'NewProjectsListView' (Name='NewProjectsListView'); target property is 'NoTarget' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'SearchResultsTemplates' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=SearchResultsTemplates; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesCommand' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesCommand; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesText' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesText; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Name' (type 'String')
    System.Windows.Data Error: 40 : BindingExpression path error: 'HasSearchResults' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=HasSearchResults; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'NewProjectsListView' (Name='NewProjectsListView'); target property is 'NoTarget' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesCommand' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesCommand; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesText' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesText; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Name' (type 'String')
    System.Windows.Data Error: 40 : BindingExpression path error: 'HasRecentTemplates' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=HasRecentTemplates; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'NewProjectsListView' (Name='NewProjectsListView'); target property is 'NoTarget' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'RecentTemplates' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=RecentTemplates; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ItemsControl' (Name=''); target property is 'ItemsSource' (type 'IEnumerable')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesCommand' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesCommand; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Command' (type 'ICommand')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesText' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesText; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'Button' (Name=''); target property is 'Name' (type 'String')
    System.Windows.Data Error: 40 : BindingExpression path error: 'MoreTemplatesText' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=MoreTemplatesText; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
    System.Windows.Data Error: 40 : BindingExpression path error: 'IsExpanded' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=IsExpanded; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'ToggleButton' (Name=''); target property is 'NoTarget' (type 'Object')
    System.Windows.Data Error: 40 : BindingExpression path error: 'IsVisible' property not found on 'object' ''PolicyBasedDataSource' (HashCode=55023063)'. BindingExpression:Path=IsVisible; DataItem='PolicyBasedDataSource' (HashCode=55023063); target element is 'GetStartedView' (Name='GettingStartedControl'); target property is 'Visibility' (type 'Visibility')
    System.Windows.Data Error: 1 : Cannot create default converter to perform 'one-way' conversions between types 'System.Windows.Media.Brush' and 'System.Windows.Media.Color'. Consider using Converter property of Binding. BindingExpression:Path=Background; DataItem='StackPanel' (Name='TaskStatusStackPanel'); target element is 'StackPanel' (Name='TaskStatusStackPanel'); target property is 'ImageBackgroundColor' (type 'Color')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='#00FFFFFF' BindingExpression:Path=Background; DataItem='StackPanel' (Name='TaskStatusStackPanel'); target element is 'StackPanel' (Name='TaskStatusStackPanel'); target property is 'ImageBackgroundColor' (type 'Color')
    System.Windows.Data Error: 40 : BindingExpression path error: 'isPopupOpen' property not found on 'object' ''TaskStatusCenterCompartmentViewModel' (HashCode=5160142)'. BindingExpression:Path=DataContext.isPopupOpen; DataItem='TaskStatusCenterCompartment' (Name='TaskStatusCenter'); target element is 'TaskStatusCenterCompartment' (Name='TaskStatusCenter'); target property is 'IsPopupOpen' (type 'Boolean')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='0' MultiBindingExpression:target element is 'GlobalSearchPopup' (Name='Popup'); target property is 'Height' (type 'Double')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='0' MultiBindingExpression:target element is 'GlobalSearchPopup' (Name='Popup'); target property is 'Width' (type 'Double')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='0' MultiBindingExpression:target element is 'GlobalSearchPopup' (Name='Popup'); target property is 'Width' (type 'Double')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='0' MultiBindingExpression:target element is 'GlobalSearchPopup' (Name='Popup'); target property is 'Height' (type 'Double')
    System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='SearchItemResultTemplate'
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' MultiBindingExpression:target element is 'ListBoxItem' (Name=''); target property is 'Name' (type 'String')
    System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' MultiBindingExpression:target element is 'ListBoxItem' (Name=''); target property is 'Name' (type 'String')
    System.Windows.Data Warning: 40 : BindingExpression path error: 'Icon' property not found on 'object' ''GlobalSearchCategoryProviderDataSource' (HashCode=46680953)'. BindingExpression:Path=Icon; DataItem='GlobalSearchCategoryProviderDataSource' (HashCode=46680953); target element is 'Image' (Name='ItemIcon'); target property is 'Source' (type 'ImageSource')
    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'ListBoxItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ListBoxItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')
    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'ListBoxItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
    System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ListBoxItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')
As usual any documentation on how to properly create custom start pages is non-existent or at least woefully out of date, so this will probably require some trial & error :(

**Comment by yannduran** [comment]
Same here

**Comment by stephanemathis** [comment]
Same for me, too bad.

**Comment by BladeMF** [comment]
Same here, but started 15.5.1.

**Comment by Gluck1312** [comment]
Same here. Have plan to fix it?

**Comment by Danielku15** [comment]
I will try to fix the problem these days. I am currently quite busy but will do my best to get it done. The structure of the new startpage is quite a nightmare when it comes to injecting custom controls there.

**Comment by Danielku15** [comment]
New Version 1.15 is published to the marketplace and should be compatible again with all VS versions.

**Comment by rwjdk** [comment]
Just install and work as intended... Thank you so much for fast bug-fix and in general for an awesome extension :-)

**Comment by IngbertPalm** [comment]
Same here. Works with version 15.5.

Unfortunately doesn't work with the latest VS preview (15.6 Preview 1.0).
The risk is high that with the next update there will be again a breaking change from MS :-(

Thank you for this great extension :-)

**Comment by yannduran** [comment]
It's working for me again too. I love this extension!

Thanks so much Daniel!
