### ISSUE TITLE
Xamarin.Android project hangs on open if opened from start page link

### ISSUE THREAD

**Issue by BladeMF** [Danielku15/BetterStartPage#30]
If a Xamarin.Android project is opened using a custom link from the start page (the part that the extension creates), it hangs on open. If the same project is opened from Recent or from the Windows Explorer, it opens perfectly.

If I have time I will try to find it myself and create a pull request.

**Comment by Danielku15** [comment]
I gave it a try today to open a Solution with the latest Visual Studio (2017, 15.5) and I could open it without issues.  Also when I open a Xamarin.Android csproj it opens normally. 

Can you still reproduce this issue with the latest updates? If yes, what version are you using?

**Comment by BladeMF** [comment]
I apologize, it seems to be working now. I am not sure what update fixed it - it opened 3 out of 3 times. Before it hung 2 of 3 times on Preparing Solution. You can close this.

**Comment by Danielku15** [comment]
Awesome, closing this defect.
