### ISSUE TITLE
Will not save New Groups and solutions in Favorites

### ISSUE THREAD

**Issue by RoyBradley** [Danielku15/BetterStartPage#31]
When I configure my solutions in the Favorites area they are not saved. When I reopen VS 2017 they are gone

**Comment by Danielku15** [comment]
Be sure not to have multiple VS instances open when making changes to your projects. Visual Studio has an annoying behavior with its settings. To be sure everything is working I recommend this steps: 

- Launch 1 VS
- Make your changes
- Close and reopen the start page to verify the changes
- Restart VS to make VS write the settings to the disk/registry.

**Comment by RoyBradley** [comment]
Thank you
