### ISSUE TITLE
Visual Studio 2017 15.6 Compatibility

### ISSUE THREAD

**Issue by lzl1918** [Danielku15/BetterStartPage#34]
The start page in 15.6 is not appearing like demonstrated.

My Visual Studio reports several errors when I try to build the source code.

**Comment by Danielku15** [comment]
I will look into getting the plugin again working on the latest Update. Microsoft is always changing the internal structures which break the plugin. 

To build the source you need to have old Visual Studio versions installed. To have compatibility with old VS versions I need to use some old VSSDK dlls.

**Comment by lzl1918** [comment]
The tutorial given by doc.microsoft.com of customizing a visual studio start page is quite different from this repo, which makes me quite confused. I tried to follow the tutorial, and I successfully let my page loaded and breakpoints hit when debugging in experimental env.

**Comment by Danielku15** [comment]
I just checked again with the latest update BetterStartPage is perfectly working fine. Please be sure to update VS and the Plugin to the latest version:
![image](https://user-images.githubusercontent.com/674916/39664676-de18bf9c-5086-11e8-89bd-b2c3478c97f9.png)

**Comment by Danielku15** [comment]
Maybe as an additional info: I just published a version 1.17 which supports auto-updates of the extension.
