### ISSUE TITLE
Not working in VS2017 (15.8.0)

### ISSUE THREAD

**Issue by willemodendaal** [Danielku15/BetterStartPage#36]
I installed the extension, changed the default start page in Startup options and restarted visual studio.

A start page renders that looks as follows. Right-click does not do anything (no context menu to edit):

![image](https://user-images.githubusercontent.com/915354/43840712-9a039a4e-9b21-11e8-9678-1f897ae29617.png)

Definitely configured in options:

![image](https://user-images.githubusercontent.com/915354/43840733-a89cab86-9b21-11e8-9350-15c46a55f098.png)

**Comment by Danielku15** [comment]
Any reason why you still use 15.5.4? I recommend upgrading VS to the latest version.

**Comment by silkfire** [comment]
Not working as of VS2017 15.8.0. Getting the same empty page as willemodendaal.

**Comment by devtony42** [comment]
I'm seeing the same thing as @silkfire -- BSP was working fine in 15.7.x as of this morning. Upgraded to 15.8 just a short while ago and I'm getting the blank start page that @willemodendaal initially described.

**Comment by Danielku15** [comment]
You're right. In the latest updates Microsoft again made changes to their internal models. I will work on it as soon as possible. 

It's really terrible that the internal models change that often. Maybe I will find a better way of creating them.

**Comment by maisoui** [comment]
same here.
Thank you for your job. Great extension!

**Comment by Danielku15** [comment]
Problem solved. I was able to find a better system to create the original start page than calling tons of internal functions. This solution should be now more future proof. Version 1.18 is available on the Marketplace.

**Comment by stijnherreman** [comment]
I guess due to the changes, VS 15.7.x is no longer supported? I just get a blank page.

I'm not yet upgrading due to a bug in 15.8.x that breaks unit test running.

**Comment by Danielku15** [comment]
It's not possible for me to test on all versions for me as also I am only running on one version. 

 If you could check the [ActivityLog](https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/) for errors maybe we can find out what's happening. With my latest changes that should be more future proof I did not check if it works for older versions.

**Comment by stijnherreman** [comment]
There are no errors or warnings in the ActivityLog, the only entries are:

```
Begin package load [BetterStartPage.BetterStartPagePackage, BetterStartPage, Version=1.18.0.0, Culture=neutral, PublicKeyToken=8241d264d40ca15b]
End package load [BetterStartPage.BetterStartPagePackage, BetterStartPage, Version=1.18.0.0, Culture=neutral, PublicKeyToken=8241d264d40ca15b]
Begin export of category 'Environment_StartPage' ({255FE6D3-A0AE-4076-A509-D581B2BE4F9E}) from package 'Visual Studio Environment Package' ({DA9FB551-C724-11D0-AE1F-00A0C90FFFC3}). 3363820 KB of virtual memory currently available.
End export of category 'Environment_StartPage' ({255FE6D3-A0AE-4076-A509-D581B2BE4F9E}). 3363820 KB of virtual memory currently available.
```

No worries though, I'll just wait for the bug fix by Microsoft and then upgrade to the latest version.
