### ISSUE TITLE
Blank page since recent update

### ISSUE THREAD

**Issue by petertcooper** [Danielku15/BetterStartPage#37]
Since the recent update better start just shows a blank white page. I can still see my projects in the "Open Favourite" menu.

I've tried uninstalling and reinstalling the extension with no change.

Do I need to delete / reset the config? If so, where can I find it?

**Comment by EddieGreen** [comment]
Ditto.

The extension hasn't been updated for a while but has only now stopped working. Since extensions are now auto-updated, not sure what other extensions have been updated that might have affected it.

**Comment by petertcooper** [comment]
On the Visual Studio gallery page it shows last update was 10 days ago, although I can't see any code changes on github that relate to that.

https://marketplace.visualstudio.com/items?itemName=Danielku15.BetterStartPage

**Comment by EddieGreen** [comment]
You're absolutely right. The lack of noted code changes was what I was going on. turning auto-update off.

**Comment by Danielku15** [comment]
Looks like I forgot to push the latest sources after my changes. The project is still active ;) 

Please be sure to update Visual Studio 2017 to the latest version. So far I wasn't able to test backwards compatibility on VS2017 but with the latest VS updates it the plugin works. See #36 for details.

**Comment by EddieGreen** [comment]
The plugin now works since updating VS from 15.7.6 to 15.8.2. 

Thanks @Danielku15 for input and your development time. It's a very useful plugin.

**Comment by petertcooper** [comment]
Yep same for me - upgrading to 15.8.2 has resolved the issue. Thanks a lot!

**Comment by Danielku15** [comment]
Awesome, then I will close this issue 😄
