### ISSUE TITLE
VS2015 support

### ISSUE THREAD

**Issue by stevehansen** [Danielku15/BetterStartPage#8]
Adding the correct tag for VS2015 support in your source.extension.manifest works.

      <VisualStudio Version="14.0">
        <Edition>Pro</Edition>
      </VisualStudio>

Running the extension at the moment in VS2015 :smile:

**Comment by mterwoord** [comment]
@Danielku15 Any luck with VS2015 support yet?

**Comment by Danielku15** [comment]
Hi there. 
I didn't investigate into VS2015 yet. But in this minute I am upgrading to VS2015 Community Edition and I'll check if it's easily possible to make a cross-version BetterStartPage

**Comment by Danielku15** [comment]
I just released Version 1.5 of BetterStartPage with VS2015 support.
